title: [DRAFT] Global Advanced Analytics | Data Science Team Best Practices
description: A test site for sharing GAA best practices via GitHub Pages, Just the Docs template, & Google Domains.
theme: just-the-docs

url: https://Jenna-Williams.github.io/GAA-Best-Practices

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  

